# Skellett the addon with the beast name!
# By the one and only LimeGlass

version: "1.7.2c"

# The syntax debug will change the colour of the found syntax option. That way it's easier to tell if that syntax was registered out of all the debug messages.
syntaxDebug: "Sound"
debug: false

# Disables the warning message saying a syntax can't be registered due to current spigot version
DisableCompatableWarning: false

# In the center message effect. This changes the length of the centered character.
CenterMessageSize: 62

#You can customize the syntax of all feudal syntax here
#So like [(the|all)] [of] [the] Feudal [kingdom] fighter[[']s] of %kingdom%
#The Feudal [kingdom] portion could be anything.
FeudalSyntaxPrefix: "Feudal [kingdom]"

PluginHooks:

# This allows for custom tablist players using plugin https://www.spigotmc.org/resources/api-tablistapi-1-7-1-8-1-9.9667/
  TabListAPI: false
# The TabClearPlayer tells skellett if it should clear just Tab Items or clear players and Tab Items when using the clear tablist expression.
  TabClearPlayer: false

  LibsDisguises: false

# Fedual: https://www.spigotmc.org/resources/feudal-completely-configurable.22873/
  Feudal: false

# OITB: https://www.spigotmc.org/resources/%E2%99%9B-one-in-the-battle-advanced-%E2%99%9B-unlimited-fun-%E2%99%A5-for-all-kinds-of-players-%E2%99%A5.24702/
  OITB: false
  
  ProtocolSupport: false
  
# http://squidhq.com/
  SquidHQ: false

# If you use Citizens https://www.spigotmc.org/resources/citizens.13811/
  Npc: false

# If you use zPermissions https://dev.bukkit.org/projects/zpermissions
  zPermissions: false